apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecommerce-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ecommerce
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gateway
          - auth
          - products
          - orders
          - users
  endpoints:
    - port: http
      path: /metrics
      interval: 15s