global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['fashion-ecommerce-gateway:8000']

  - job_name: 'auth'
    static_configs:
      - targets: ['fashion-ecommerce-auth:8000']

  - job_name: 'product-service'
    static_configs:
      - targets: ['fashion-ecommerce-products:8000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['fashion-ecommerce-orders:8000']

  - job_name: 'orders'
    static_configs:
      - targets: ['fashion-ecommerce-orders-management:8000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['fashion-ecommerce-users:8000']