apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yml
  - secrets.yml
  - k8s/database/statefulset.yml
  - k8s/database/service.yml
  - k8s/backend/gateway.yml
  - k8s/backend/auth.yml
  - k8s/backend/products.yml
  - k8s/backend/orders.yml
  - k8s/backend/users.yml
  - k8s/backend/service-monitor.yml
  - k8s/frontend/deployment.yml

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - k8s/database/configmap.yml